### PR TITLE
Adding Martijn

### PR DESCRIPTION
**Pull request by karianna**

### CODE REVIEW

**Comment by OndroMih** [comment]
@karianna I gave you access to all I could give, I don't have direct access to jcpevangelists org, therefore I only gave you admin to the jcpevangelists repo in the org (which I am owner of).
@atheedom will need to give us all access to the Twitter account and the ee-central github org.

**Comment by atheedom** [comment]
@karianna  and @OndrejM are you happy for me to add username/passwords to a shared google doc?

**Comment by karianna** [comment]
Yeah it's not super secure but I don't think we're running anything critical

Cheers,
Martijn

**Comment by OndroMih** [comment]
Yes, private google doc would be fine. 

Grouptweet.com seems also good to manage a group account like ee-central, from anyone's private account, see my mail: https://groups.google.com/d/msg/ee-central/KeUkXKNnrXU/mWDuJdn6FgAJ

**Pull request merged**
